//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faculty
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyEmployee
    {
        public string fac_Name { get; set; }
        public string fac_Address { get; set; }
        public string fac_Age { get; set; }
        public string fac_Depa { get; set; }
    }
}
